팀 생성일과 회원가입일을 추가했습니다.
LM-channel-team-project/Team-Auto-Matcher pull request #129
Opened 2021-08-18 03:59 UTC by Ho-s

![image](https://user-images.githubusercontent.com/71132893/129834627-186807fc-5443-489f-abcf-7bd36ceecb43.png)

회원가입일은 personal dashboard에 나타낼 필요 없을 것 같아 나타내지 않았습니다.
확인 해주시면 머지 하기 전에 aws dynamodb 업데이트 하겠습니다.
스키마 변경되었으니 스키마 노션 참고하셔서 변경해주세요.

2021-08-18 12:32 UTC, pkiop requested changes
생성일 string으로 저장하는 것 보다 date 객체 그대로 저장하는게 좋을 것 같아요
aws에서도 date 값 지원하니까 한번 해보시면 배우는 것 많으실겁니다!

2021-08-19 06:17 UTC, Ho-s commented
> 생성일 string으로 저장하는 것 보다 date 객체 그대로 저장하는게 좋을 것 같아요
> aws에서도 date 값 지원하니까 한번 해보시면 배우는 것 많으실겁니다!

아하 수정하도록 하겠습니다!

2021-08-19 07:25 UTC, lhk3337 approved these changes

2021-08-19 09:38 UTC, pkiop commented on client/src/component/orgamisms/DetailModal/NoticeAddForm/index.tsx
> +  const [date, setDate] = useState<string>(new Date().toISOString().substring(0, 10));
이걸 그냥 useState<Date>(new Date()) 헤서 동작하게 하시면 됩니다

2021-08-20 11:58 UTC, pkiop approved these changes
고생하셨습니다!

2021-08-20 12:22 UTC, merged