매칭 대기열 수정
LM-channel-team-project/Team-Auto-Matcher pull request #28
Opened 2021-05-21 07:37 UTC by lhk3337

## 매칭 대기열

![55408fc5d8e5](https://user-images.githubusercontent.com/44824320/119099406-d2ff5c00-ba51-11eb-92eb-61b190620dec.gif)

state를 이용하여 화살표를 누르면 각각 개발 분야에 맞는 리스트가 표시되도록  매치 대기열을 수정 하였습니다.

2021-05-21 08:30 UTC, lhk3337 commented
## AWS AppSync의 스키마 type personDashboard부분 수정 하시면 됩니다.
```graphql
type personDashboard {
	id: ID!
	name: String
	skills: [String]
	team: [String]
	outline: String
	field: String
	devExp: String
	contents: [dashboardContent]
}
```

## teamAutoMacher_personDashboard Item table
```JSON
{
  "contents": [
    {
      "text": "재밌게 하겠습니다..",
      "title": "자기소개"
    },
    {
      "text": "재밌게 합시다..",
      "title": "하고싶은 말"
    }
  ],
  "devExp": "1년",
  "field": "Backend",
  "id": "001",
  "name": "user3",
  "outline": "열심히 하겠습니다",
  "skills": [
    "React",
    "MongoDB",
    "Express"
  ],
  "team": [
    "팀 구하는중"
  ]
}
```

2021-05-21 15:57 UTC, Ho-s approved these changes
고생하셨슴다~

2021-05-21 16:31 UTC, lhk3337 commented on client/src/page/MatchWait/style.ts
> +  position: sticky;
네네 수정 하였습니다

2021-05-22 07:35 UTC, pkiop commented on client/src/page/Dashboard/Personal/index.tsx
> +import { listPersonDashboard } from '../../../graphql/matchQueries';
경로 
`import { listPersonDashboard } from 'graphql/queries';`
이걸 보시면 경로 앞에 아무것도 안 적었을 때 src폴더 기준으로 찾도록 되어 있어요~
굳이 ../../../이렇게 안 찾으러 가도 됩니다

2021-05-22 07:38 UTC, pkiop requested changes

2021-05-22 07:38 UTC, pkiop commented on client/src/page/Dashboard/Personal/style.ts
> +  padding-top: 20px;
css 단위는 rem이나 em으로 통일할게요!

2021-05-22 07:38 UTC, pkiop commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
이거는 왜 필요한가요?

2021-05-22 09:37 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +import { listPersonDashboard } from '../../../graphql/matchQueries';
네 수정하겠습니다.

2021-05-22 09:42 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/style.ts
> +  padding-top: 20px;
네네 알겠습니다.

2021-05-22 09:44 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
Failed to compile. 가 발생하여 임시적으로 eslint를 disable 해놓았습니다.

2021-05-22 10:41 UTC, pkiop commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
그 밖에 다른 에러메세지는 없나요? 해결하려면 할 수 있을 것 같기도 해서요!

2021-05-22 10:58 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
<img width="1005" alt="스크린샷 2021-05-22 오후 7 57 28" src="https://user-images.githubusercontent.com/44824320/119224144-01effd80-bb38-11eb-9bd2-30f923367485.png">

에러메시지 첨부합니다.

2021-05-22 11:42 UTC, pkiop commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
vscode eslint 익스텐션 설치해서 format on save 체크하고 파일 한번 저장해보시겠어요?

2021-05-22 12:04 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
확인해보니 format on save에 체크 되어 있습니다.

2021-05-22 13:31 UTC, pkiop commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
newline을 주면 되지 않을까요?

2021-05-22 13:38 UTC, pkiop commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
```
 const {
    loading, error, data, refetch,
  } = useQuery(
  ```
  이런식으로 바꾸면 될 것 같습니다

2021-05-22 14:17 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
저장 하면 자동적으로  const { loading, error, data, refetch } = useQuery(

변환 됩니다.

2021-05-22 20:38 UTC, pkiop commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
vscode설정중에 editor.defaultfommater인가 이런 것 있는데 이거 prettier로 수정하시면 될거에요

2021-05-23 01:11 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +/* eslint-disable */
prettier로 되어 있으면 자동적으로 바뀌고
None으로 되어 있으면 
const {
   loading, error, data, refetch,
 } = useQuery(
되어 일단 None으로 변경 후 저장 하였습니다.

2021-05-23 01:28 UTC, pkiop approved these changes
고생하셨습니다👍

2021-05-23 02:43 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +  const {
eslint 에러 
**Expected a line break after this opening brace  ->      Object-curly-newline
Expected a line break after this closing brace       ->     Object-curly-newline**  

저장하면 자동적으로 const {loading, error, data, refetch,} =useQuery(... 로 변경

vscode의 editor.defaultformmater에서 Prettier에서 None으로 변경 후 파일 저장

2021-05-23 02:43 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +    const result = { ...obj };
eslint 에러
Assignment to property of function parameter 'obj'  -> no-param-reassign
parameter obj 객체를 if문에 obj로 할당함.
obj객체를 변수로 선언 후 변수를 할당함

2021-05-23 02:43 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +  const users = items.reduce((obj: any, user: any) => {
'user'  is already declared in the upper scope on line 18 -> no-shadow
parameter user와 변수명이 같아서 에러발생.
변수명을 users로 변경

2021-05-24 06:21 UTC, youngrongoh commented on client/src/page/Dashboard/Personal/index.tsx
> +          {index === current && (
혹시 여기서 배열을 순회 하도록 작성해주신 이유가 있을까요??

`current` 인덱스와 일치하지 않는 필드에 대해서 `<S.Container />` 컴포넌트가 생성되고 있어서요..!
반복 없이도 `Object.keys(users)[current]`를 이용해 렌더링에 필요한 데이터를 조회할 수 있을 것 같습니다😊

|map 사용|map 미사용|
|:-:|:-:|
|![사용](https://user-images.githubusercontent.com/64844815/119305092-37fdc080-bca3-11eb-8814-8d8e1c959b48.png)|![미사용](https://user-images.githubusercontent.com/64844815/119305151-4d72ea80-bca3-11eb-9f93-0df21de67d1d.png)|

2021-05-24 07:01 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +                    <S.Title>⬅️</S.Title>
발견 해주셔서 감사합니다. 
특수문자는 환경마다 다르게 표시되는 군요..  수정 하겠습니다.

2021-05-24 07:17 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +                    <S.Title>⬅️</S.Title>
알려주셔서 감사합니다. 
특수문자는 환경마다 다르게 표시되는 군요..  수정 하겠습니다.

2021-05-24 07:24 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +          {index === current && (
화살표 클릭하면 페이지 별로 분류 하기 위해 배열 순외를 사용 했습니다.  각각의  Component는 분류한 페이지 리스트들 입니다.

2021-05-24 07:56 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +          {index === current && (
<S.Container key={users}>를 Object위에 선언했는데 
<img width="672" alt="스크린샷 2021-05-24 오후 4 53 38" src="https://user-images.githubusercontent.com/44824320/119315278-a5641e00-bcb0-11eb-95e7-d55643304b5e.png">

밑에 처럼 Component 3개만 나왔습니다.
<img width="435" alt="스크린샷 2021-05-24 오후 4 53 05" src="https://user-images.githubusercontent.com/44824320/119315292-a9903b80-bcb0-11eb-826d-211cf7f20b46.png">

이렇게 선언하면 않되나요?

2021-05-24 07:57 UTC, youngrongoh commented on client/src/page/Dashboard/Personal/index.tsx
> +          {index === current && (
네! 그런데 순회 없이도 동일한 구현이 가능하고,
오히려 위에 첨부한 이미지와 같이 빈 div 박스가 생기는 상황도 방지할 수 있어서 여쭤봤습니다😊

2021-05-24 08:07 UTC, lhk3337 commented on client/src/page/Dashboard/Personal/index.tsx
> +          {index === current && (
빈 div 박스 부분 발견 해주셔서 감사합니다.

혹시 순회 없이 구현 하려면 어떻게 구현 해야 할까요??

2021-05-24 09:11 UTC, youngrongoh commented on client/src/page/Dashboard/Personal/index.tsx
> +          {index === current && (
위에 이미지 올려주신 것처럼
map 순회 코드의 위치를 변경 해주시는 방법으로도 빈 div 박스 문제는 해결이 됩니다..!

순회 없이 구현하는 것은
51번 라인에서 `field` 대신 `Object.keys(users)[current]`를 사용하고, 
58번 라인에서 `users[field]` 대신 `users[Object.keys(users)[current]]` 값을 사용하시면 됩니다🤗

여기서 반복적으로 쓰이는 부분(`Object.keys(users)`)은 변수로 선언 해주시면 더 깔끔하게,
그리고 `Object.keys` 메소드도 여러번 호출하지 않아도 되겠죠..!ㅎㅎ

2021-05-24 13:03 UTC, youngrongoh approved these changes
고생하셨습니다🤗

2021-05-24 13:38 UTC, merged

2021-05-31 04:09 UTC, lhk3337 commented
# Appsync에서
- ## 예전에 만들었던 matchWaitQueue DB 스키마 삭제 해 주세요.

```graphql

type Query {
	getMatchWaitQueue(id: ID!): matchWaitQueue
	listMatchWaitQueue(nextToken: String): matchWaitQueue_Connection
}


type matchWaitQueue {
	id: ID!
	name: String
	message: String
	stacks: [String]
	state: String
	type: String
	year: String
}

type matchWaitQueue_Connection {
	items: [matchWaitQueue]
	nextToken: String
}

```

- ## 데이터 원본에서도 matchWaitQueue 삭제 해주세요
- ## matchWaitQueue와 연결된 테이블도 삭제 해 주세요