Survey페이지와, Login페이지의 스타일을 변경하였습니다.
LM-channel-team-project/Team-Auto-Matcher pull request #32
Opened 2021-05-28 06:15 UTC by Ho-s

## Survey
![ezgif-6-4b0cea8af0a4](https://user-images.githubusercontent.com/71132893/119937253-71953b00-bfc5-11eb-8059-bb578b111a5d.gif)

## AWS appsync schema TeamAutoMatcher_Questionnaire 부분 변경해주세요.
```graphql
type TeamAutoMatcher_Questionnaire {
	id: ID!
	questionTitle: String!
	questionBrief: String!
	priority: Int!
	questionList: [String]!
	bDuplicate: Boolean!
}
```

## DynamoDB에 질문 목록 테이블에 항목 추가해주세요. 저는 테이블명이 MyModelType으로 되어있습니다.

```mySQL
{
  "bDuplicate": false,
  "id": "00000",
  "priority": 0,
  "questionBrief": "Dev-Field",
  "questionList": [
    "프론트엔드",
    "백엔드",
    "안드로이드",
    "IOS",
    "AI",
    "데이터",
    "Devops"
  ],
  "questionTitle": "하고싶은 개발 분야를 선택하세요."
}

{
  "bDuplicate": true,
  "id": "00001",
  "priority": 1,
  "questionBrief": "Available Stack",
  "questionList": [
    "설문 1로 돌아가 개발 분야를 선택해주세요."
  ],
  "questionTitle": "사용가능한 기술 스택을 골라주세요."
}

{
  "bDuplicate": false,
  "id": "00002",
  "priority": 2,
  "questionBrief": "How Long",
  "questionList": [
    "~ 1month",
    "1month ~ 3months",
    "3months ~ 6months",
    "6months ~ 1year",
    "1year ~ 2year",
    "2year ~"
  ],
  "questionTitle": "프로그래밍을 공부한 지 얼마나 되었나요?"
}

{
  "bDuplicate": false,
  "id": "00004",
  "priority": 3,
  "questionBrief": "Activity Period",
  "questionList": [
    "~ 1month",
    "~ 2months",
    "~ 3months",
    "~ 4months",
    "~ 6months"
  ],
  "questionTitle": "예상 활동기간을 설정해주세요."
}

{
  "bDuplicate": true,
  "id": "00005",
  "priority": 4,
  "questionBrief": "Available Time",
  "questionList": [
    "평일 9AM~12PM",
    "평일 12PM~6PM",
    "평일 6PM~12AM",
    "주말 9AM~12PM",
    "주말 12PM~6PM",
    "주말 6PM~12AM"
  ],
  "questionTitle": "활동 가능 시간을 설정해주세요."
}

{
  "bDuplicate": false,
  "id": "00006",
  "priority": 5,
  "questionBrief": "Off Or On",
  "questionList": [
    "오프라인",
    "온라인"
  ],
  "questionTitle": "선호하는 진행 방식을 선택해주세요."
}

{
  "bDuplicate": false,
  "id": "00007",
  "priority": 6,
  "questionBrief": "Experienced",
  "questionList": [
    "경험 있음",
    "경험 없음"
  ],
  "questionTitle": "팀프로젝트 경험이 있으신가요?"
}

{
  "bDuplicate": true,
  "id": "00008",
  "priority": 7,
  "questionBrief": "Important Element",
  "questionList": [
    "디자인",
    "기능",
    "UI & UX",
    "일정",
    "실력",
    "친목"
  ],
  "questionTitle": "팀프로젝트에서 중요하게 생각하는 요소를 선택해주세요."
}

{
  "bDuplicate": false,
  "id": "00009",
  "priority": 8,
  "questionBrief": "Introduction",
  "questionList": [

  ],
  "questionTitle": "짧게 자기소개를 해주세요."
}

{
  "bDuplicate": false,
  "id": "00010",
  "priority": 9,
  "questionBrief": "Project",
  "questionList": [

  ],
  "questionTitle": "계획하는 프로젝트가 있다면 적어주세요."
}

{
  "bDuplicate": false,
  "id": "00011",
  "priority": 10,
  "questionBrief": "Anything",
  "questionList": [

  ],
  "questionTitle": "하고싶은 말이 있다면 적어주세요."
}
```
하나씩 추가해주시면 됩니다.

2021-05-29 05:31 UTC, pkiop commented on client/src/component/atoms/DirectionBtn/index.tsx
> +};
이런 용도면 typescript 에 Enum 으로 할 수 있을 것 같아요! 4~7번줄이랑 같이 enum으로 수정할 수 있을 것 같습니다

2021-05-29 05:31 UTC, pkiop commented on client/src/component/atoms/DirectionBtn/index.tsx
> +};
enum EDirection {
   BACK,
   NEXT,
}

이렇게 짤 수 있습니다

2021-05-29 05:31 UTC, pkiop commented on client/src/component/atoms/DirectionBtn/style.ts
> +    font-size: 28px;
px 말고 rem단위로 통일할게요~

2021-05-29 05:32 UTC, pkiop commented on client/src/component/atoms/ProgressBarList/index.tsx
> +  setId,
setId 없을 수도 있으면 기본 값 지정해주면 좋을 것 같아요

2021-05-29 05:32 UTC, pkiop commented on client/src/component/atoms/ProgressBarList/index.tsx
> +  Brief,
얘만 첫글자가 대문자인 이유가 있나요?

2021-05-29 05:34 UTC, pkiop commented on client/src/component/molecules/LoginBtn/index.tsx
> +      <span></span>
이건 어떤 용도인가요?

2021-05-29 05:34 UTC, pkiop commented on client/src/component/molecules/LoginBtn/style.ts
> +    background: #2894ff;
background-color로 통일할게요!

2021-05-29 05:36 UTC, pkiop commented on client/src/component/orgamisms/Questionnaire/index.tsx
> +  listQuestionnairesData,
이것도 없을 수 있으면 기본값 지정하면 좋을 것 같습니다

2021-05-29 05:38 UTC, pkiop requested changes
너무 예쁘네요..! 코멘트 남긴 것 중 ?: 로 됐던 건 수정 부탁드립니다!

2021-05-29 13:20 UTC, Ho-s commented on client/src/component/atoms/ProgressBarList/index.tsx
> +  Brief,
questionBrief를 받아오는 거라서 저도 모르게 대문자로 썼네요 ! 수정했습니다!

2021-05-29 13:22 UTC, Ho-s commented on client/src/component/molecules/LoginBtn/index.tsx
> +      <span></span>
버튼의 애니메이션을 구현하려고 넣어놓은 것입니다!

2021-05-29 13:30 UTC, Ho-s commented on client/src/component/atoms/ProgressBarList/index.tsx
> +  setId,
수정했습니다! 그런데, 초기값을 지정해주는 이유가 무엇인가요?

2021-05-29 13:47 UTC, Ho-s commented on client/src/component/atoms/DirectionBtn/index.tsx
> +};
![image](https://user-images.githubusercontent.com/71132893/120072636-d2109f00-c0cf-11eb-85c1-fefe692771ea.png)
 
이런식으로 가면 되는 건가요?

2021-05-30 12:45 UTC, pkiop commented on client/src/component/atoms/ProgressBarList/index.tsx
> +  setId,
위에서 타입이 ?: 로 되어있어서 null 값 들어오면 에러가날것같아 말씀드렸던 건데
props로 전달할때부터 null일경우가 처리되어있으면 굳이 추가 안해도 될 것 같네요

2021-05-31 01:09 UTC, Ho-s commented
eslintrc.js에 rules부분에 아래 코드 추가해주세요.

```js
    "no-shadow": "off",
    "@typescript-eslint/no-shadow": ["error"]
```

2021-05-31 04:08 UTC, youngrongoh commented on client/src/component/atoms/DirectionBtn/index.tsx
> +};
@pkiop 상신님 질문 있습니다..!
제가 생각하기로는 union type으로 써도 될 것 같고,
찾아보니 `enum`을 쓰면 tree-shaking이 안된다고 하더라구요!
지금 경우에서 `enum`을 쓰는 이유가 있는지 궁금합니다..!

2021-05-31 11:02 UTC, pkiop commented on client/src/component/atoms/DirectionBtn/index.tsx
> +};
tree-shaking 이란게 있군요 배워 갑니다!

union type 쓰면 코드에 문자열을 써야하는데 
ex) `if(direction === 'BACK')` 
코드에 문자열 넣는게 별로 좋지 않은 것 같아 enum이 좋아 보입니다.

근데 검색해보니 enum이 안티패턴이라고도 하는 것 같네요(이유는 아직 납득안가지만..)

2021-05-31 11:02 UTC, lhk3337 approved these changes

2021-05-31 11:02 UTC, pkiop approved these changes
고생하셨습니다~!

2021-05-31 11:07 UTC, lhk3337 commented on client/src/component/atoms/DirectionBtn/index.tsx
> +};
TypeScript 자료형에는 enum union등이 있었군요.  알려 주셔서 감사합니다.

2021-05-31 11:11 UTC, lhk3337 commented on client/src/page/Survey/index.tsx
> +      case '프론트엔드':
백엔드, 안드로이드, 프론트엔드를 한글로 적으신 이유가 화면에 표시하기 위해서 선언 하신 것인가요?

2021-05-31 12:28 UTC, youngrongoh approved these changes
고생하셨습니다!

2021-05-31 12:33 UTC, Ho-s commented on client/src/page/Survey/index.tsx
> +      case '프론트엔드':
![image](https://user-images.githubusercontent.com/71132893/120193799-c8b23e80-c257-11eb-9e17-94ccde91d6c6.png)

아뇨, 1번 질문에서 answer로 넘어오는 답이 위에 보이시는 것처럼 전부 한글이기 때문에, 그거에 따라서 표시해주는 것입니다!

2021-05-31 12:37 UTC, Ho-s commented on client/src/component/atoms/DirectionBtn/index.tsx
> +    <div>There need to be a direction</div>
좋은 지적 감사합니다! 수정 완료했습니다~

2021-05-31 14:07 UTC, lhk3337 commented
고생 많으셨습니다.

2021-05-31 14:11 UTC, lhk3337 approved these changes

2021-06-01 02:33 UTC, merged