Team Dashboard 추가
LM-channel-team-project/Team-Auto-Matcher pull request #34
Opened 2021-06-01 10:24 UTC by lhk3337

![teamDashboard](https://user-images.githubusercontent.com/44824320/120305773-2011e680-c30c-11eb-958d-895ac644d803.gif)

## [AppSync] - [스키마] - [type teamDashboard]에서 state가 추가 되었습니다.
```graphql
type teamDashboard {
	id: ID!
	name: String!
	people: [String]
	skills: [String]
	outline: String
	contents: [dashboardContent]
	state: String!
}
```

## TeamAutoMatcher_teamTable에서 state 필드가 추가 되었습니다. 
state값은 모집중, 진행중, 종료 3가지 중 하나입니다.

```JSON
{
  "contents": [
    {
      "text": "출시를 목적으로 하는 앱을 개발하려 합니다",
      "title": "구현하고자 하는 것"
    },
    {
      "text": "아이디어를 내고 있는 중입니다.",
      "title": "진행 상황"
    }
  ],
  "id": "0001",
  "name": "team3",
  "outline": "한줄 소개 입니다.",
  "people": [
    "user1",
    "user2",
    "user3"
  ],
  "skills": [
    "React",
    "MongoDB",
    "GraphQL",
    "SQL",
    "JS",
    "CSS",
    "HTML"
  ],
  "state": "모집중"
}
```

```JSON
{
  "contents": [
    {
      "text": "출시를 목적으로 하는 앱을 개발하려 합니다",
      "title": "구현하고자 하는 것"
    },
    {
      "text": "아이디어를 내고 있는 중입니다.",
      "title": "진행 상황"
    }
  ],
  "id": "0002",
  "name": "team1",
  "outline": "한줄 소개 입니다.",
  "people": [
    "user1",
    "user2",
    "user3"
  ],
  "skills": [
    "React",
    "MongoDB",
    "GraphQL",
    "SQL",
    "JS",
    "CSS",
    "HTML"
  ],
  "state": "진행중"
}
```

```JSON
{
  "contents": [
    {
      "text": "출시를 목적으로 하는 앱을 개발하려 합니다",
      "title": "구현하고자 하는 것"
    },
    {
      "text": "아이디어를 내고 있는 중입니다.",
      "title": "진행 상황"
    }
  ],
  "id": "0003",
  "name": "team12",
  "outline": "한줄 소개 입니다.",
  "people": [
    "user1",
    "user2",
    "user3"
  ],
  "skills": [
    "Vue",
    "MongoDB"
  ],
  "state": "종료"
}
```

2021-06-01 12:03 UTC, pkiop commented on client/.eslintrc.js
> +    '@typescript-eslint/no-shadow': ['error'],
이건 왜 필요한건가요?

2021-06-01 12:07 UTC, pkiop commented on client/src/page/Dashboard/Team/index.tsx
> +import * as Team from './style';
첫글자로 할꺼면 둘 다 첫글자로 P, T 로 하거나 컴포넌트 이름으로 할꺼면 P를 Personal로 바꾸는게 좋아 보여요

2021-06-01 12:08 UTC, pkiop commented on client/src/page/Dashboard/Team/style.ts
> +  width: 123em;
em 은 padding이나 margin에 사용하고 나머지는 rem이 좋아보이는데 다른 의견이 있으신가요?

2021-06-01 12:10 UTC, pkiop commented on client/src/page/Dashboard/Team/index.tsx
> +    // const people = team.people.map((person: string) => <div>{person}</div>);
지워도 될 것 같습니다!

2021-06-01 12:12 UTC, Ho-s commented on client/.eslintrc.js
> +    '@typescript-eslint/no-shadow': ['error'],
이건 제가 추가해달라고 말씀드린건데, enum 때문에 자꾸 에러가 나서 찾아보니까 이걸로 해결하라고 하더라고요!

[https://stackoverflow.com/questions/63961803/eslint-says-all-enums-in-typescript-app-are-already-declared-in-the-upper-scope](https://stackoverflow.com/questions/63961803/eslint-says-all-enums-in-typescript-app-are-already-declared-in-the-upper-scope)

2021-06-01 12:43 UTC, Ho-s approved these changes
수고하셨슴다!

2021-06-01 12:49 UTC, lhk3337 commented on client/src/page/Dashboard/Team/index.tsx
> +import * as Team from './style';
네 통일성 있게 Personal, Team으로 수정하겠습니다.

2021-06-01 12:49 UTC, lhk3337 commented on client/src/page/Dashboard/Team/style.ts
> +  width: 123em;
em과 rem의 차이점을 잘몰라서 em으로 선언했습니다.

2021-06-01 12:49 UTC, lhk3337 commented on client/src/page/Dashboard/Team/index.tsx
> +    // const people = team.people.map((person: string) => <div>{person}</div>);
네네 수정하겠습니다.

2021-06-02 12:13 UTC, pkiop requested changes
padding, margin 말고는 rem을 쓰는게 좋아 보입니다
https://webdesign.tutsplus.com/ko/tutorials/comprehensive-guide-when-to-use-em-vs-rem--cms-23984

2021-06-02 14:30 UTC, youngrongoh commented on client/src/page/Dashboard/Team/style.ts
> +  width: 123em;
> em 은 padding이나 margin에 사용하고 나머지는 rem이 좋아보이는데 다른 의견이 있으신가요?

저는 보통 작은 단위 혹은 재사용성이 높은 컴포넌트의 경우는
`em` 단위로 사이징해서 상위 컴포넌트의 폰트 사이즈에 따라 변경되도록 했었습니다.
사이징을 `em`으로 해주고 상위 컴포넌트에서 폰트사이즈만 바꿔주면 비율을 유지하면서 크기만 커지니까요..!

그런데 우리 프로젝트에는 styled-component가 있어서 `rem`으로 해도 사용하는 곳에서 원하는대로 변경할 수 있는 것 같네요..!

결론은.. `rem`으로 통일해도 될것 같습니다 ㅎㅎ

2021-06-02 14:31 UTC, youngrongoh approved these changes
고생하셨습니다!

2021-06-02 14:39 UTC, pkiop commented on client/src/page/Dashboard/Team/style.ts
> +  width: 123em;
em이 그런면에서 좋긴 한데 그렇게 바뀌어야 할만한게 padding이나 margin이라고 생각해서요 그래서 꼭 rem 통일할 필요 없이 em을 쓰고싶으시면 이 곳에 써도 좋을 것 같습니다. 

모든 스타일에 em을 쓰셔서 잘 알고 쓰셨으면 상관없는데 모르고 쓰셨으면 굳이 em 쓰지 말고 rem쓰셨으면 좋겠습니다~

2021-06-02 15:16 UTC, lhk3337 commented on client/src/page/Dashboard/Team/style.ts
> +  width: 123em;
### em과 rem차이점에 대해 알려주셔서 감사합니다.
- em 단위는 지정된 요소의 폰트 크기를 기준으로 합니다.
- rem 단위는 html 요소의 폰트 크기를 기준으로 합니다.
- em 단위는 모든 상위 부모 요소로부터의 폰트 크기를 상속받으면서 영향을 받을 수 있습니다.
- rem 단위는 브라우저에 설정된 폰트 크기를 상속받는 특성이 있습니다.

2021-06-02 15:32 UTC, lhk3337 commented on client/src/page/Dashboard/Team/style.ts
> +  width: 123em;
padding과 margin을 제외하고 em에서 rem으로 변경하였습니다.

2021-06-03 00:51 UTC, pkiop approved these changes
고생하셨습니다!!😊

2021-06-03 00:55 UTC, merged